widget = "featurette"  # See https://sourcethemes.com/academic/docs/page-builder/
headless = true  # This file represents a page section.
active = true  # Activate this widget? true/false
weight = 30  # Order that this section will appear.

title = "Meta-Analysis Domains from toml"
subtitle = ""

[[feature]]
  icon = "comments"
  icon_pack = "fas"
  name = "Early Language"
  description = "How do children learn their native language?"
  meta_analyses = "22"
  effect_sizes = "10"
  papers = "100"
  subjects = "10,000"
  link = "/explore/datasets"
  
[[feature]]
  icon = "book"
  icon_pack = "fas"
  name = "Cognitive Development"
  description = "What is the nature of children's understanding?"
  link = "/explore/datasets"
